### ISSUE TITLE
fails to compile

### ISSUE THREAD

**Issue by svalaskevicius** [jatcwang/difflicious#36]
```
[E] Unexpected error when compiling xxx-test: dotty.tools.dotc.core.TypeError$$anon$1: Toplevel definition split is defined in
[E]   ~/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/jatcwang/difflicious-core_3/0.4.2/difflicious-core_3-0.4.2.jar(difflicious/DifferGen.tasty)
[E] and also in
[E]   ~/.cache/coursier/v1/https/repo1.maven.org/maven2/com/softwaremill/magnolia1_3/magnolia_3/1.0.0/magnolia_3-1.0.0.jar(magnolia1/Derivation.tasty)
[E] One of these files should be removed from the classpath.
```

**Comment by jatcwang** [comment]
Hi, is this error happening while compiling your project? Which Scala version are you using?
Would be great if you can provide a minimal reproduction to help us get to the bottom of this. Thanks!

**Comment by svalaskevicius** [comment]
hi. yes, but only if I use auto derivation (import auto.derived) , it doesn't fail if I use the derived method explicitly

using the new scala 3.5

I'll try to get a minimal project setup but it will need to be later on / another day when I can allocate some more time as its a non-trivial task :)

thanks!

**Comment by jatcwang** [comment]
Thanks @svalaskevicius that's useful information. I'm currently trying to upgrade this project's dependencies and I can see errors around automatic derivation too. I'm not sure if its' related, so feel free to wait on the reproduction while I investigate.

**Comment by jatcwang** [comment]
I have published 0.4.3, but I don't think the issue I faced (with munit) is related. Can you try the latest version and see?

**Comment by svalaskevicius** [comment]
hi, it's working! :) albeit makes the compile time much slower, so I think I'll stick with the defined givens and import them in the test :)

**Comment by jatcwang** [comment]
If you define the givens explicitly (e.g. in companion object) then you shouldn't need to import them. That should also make compilation faster over automatic derivation :)
